### ISSUE TITLE
Region is missing

### ISSUE THREAD

**Issue by pramaths** [daytimedrinkingclub/shipstation#13]
![image](https://github.com/user-attachments/assets/27d38f03-4b56-4fc5-8fb3-4827cbdf36b9)
Showing error for region, but there is no mention of Region in env

**Comment by pramaths** [comment]
@ptmaroct  how to resolve this? am I missing any field in env

**Comment by ptmaroct** [comment]
@pramaths this is the S3 region, which comes from **BUCKETEER_AWS_REGION** env variable. You can comment out the usages of methods from https://github.com/daytimedrinkingclub/shipstation/blob/main/server/services/s3Service.js which are used to store websites to s3 as that websites are stored locally anyway

For local running
