### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ptmaroct** [daytimedrinkingclub/shipstation#23]
Currently we are using Tavily [https://tavily.com/] inside the search tool which returns the images as well for the query. We need to utlise those images whenever available from tavily response when creating components, in place of using placeholder images.

**Comment by Rehannn03** [comment]
Can you please elaborate that what is the problem and what solution do you require.

**Comment by ganeshdole** [comment]
Hi @Rehannn03, This web app uses Tavily AI to acquire real-time photos from the web; we must integrate these image responses into the actual design when creating a component for a client request. (This is my understanding.)

**Comment by satvik2131** [comment]
unable to get the issue , can it be a more descriptive ?

**Comment by ptmaroct** [comment]
This has been done
