### ISSUE TITLE
Preview device design fixes

### ISSUE THREAD

**Issue by ptmaroct** [daytimedrinkingclub/shipstation#25]
<img width="351" alt="Screenshot 2024-08-14 at 12 18 10 AM" src="https://github.com/user-attachments/assets/867b42c5-c0a9-4e80-b7b0-15d37dfac6c4">

**Comment by Jaishree2310** [comment]
Hey @ptmaroct, I would like to take this issue. Can you please assign this issue to me?
Thanks!

**Comment by ptmaroct** [comment]
@Jaishree2310 anyone can work on any issue!

**Comment by theavitw** [comment]
Can you elaborate more in this issue??
