### ISSUE TITLE
Can't login when setting up shipfast on local machine

### ISSUE THREAD

**Issue by AnshVM** [daytimedrinkingclub/shipstation#34]
I tried setting up shipfast on my local machine. Both client and server start up successfully, but when I try to login this happens:

- On first attempt, it looks like it worked, it gives the 'Welcome back' message, but when I try to click on 'Ship landing page' it prompts me to login again.
- Then when I try to login again, I keep getting 'Rate limiting exceeded' error.

Setup all API keys required as mentioned in .env.template files, and setup supabase as mentioned in the README file.

Is there any supabase specific setup required for auth to work? Apart from running setup.sql? 

![image](https://github.com/user-attachments/assets/dbe8a790-b3c1-4eaa-ad89-abb0a49ed859)

**Comment by vikaswakde** [comment]
check on localhost:3000

**Comment by AnshVM** [comment]
This works, thanks !!
Closing
