### ISSUE TITLE
fix mail authentication

### ISSUE THREAD

**Issue by akshaykamath45** [daytimedrinkingclub/shipstation#43]
I am able to sign up with any random email id, it is not authenticating when I click the `Submit` button.
Authentication happens when I click `Email me a login link `.

It is directly creating the account on click of submit button on  signup.
![image](https://github.com/user-attachments/assets/0ad5625a-810d-4a1e-bc14-43dd70dbb9aa)

**Comment by ptmaroct** [comment]
Its intentional, we decided to skip email verification.
If possible, help reset password flow using supabase
